// generated by stringer -type WorkMode; DO NOT EDIT

package main

import "fmt"

const _WorkMode_name = "EverydayWorkdaysHolidaysWorkModeNum"

var _WorkMode_index = [...]uint8{0, 8, 16, 24, 35}

func (i WorkMode) String() string {
	i -= 1
	if i < 0 || i >= WorkMode(len(_WorkMode_index)-1) {
		return fmt.Sprintf("WorkMode(%d)", i+1)
	}
	return _WorkMode_name[_WorkMode_index[i]:_WorkMode_index[i+1]]
}
